# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    restart: always
    environment:
      POSTGRES_USER: montaan
      POSTGRES_PASSWORD: montaan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
