version: '3.7'

services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: montaan
            POSTGRES_PASSWORD: montaan

    backend:
        image: node
        working_dir: /montaan/backend
        command: yarn watch
        ports:
            - 8008:8008
        restart: always
        depends_on:
            - db
        volumes:
            - ./:/montaan:cached

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pgdata:
        driver: local
