version: '3.1'

services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgconf:/etc/postgresql
            - pglog:/var/log/postgresql
        restart: always
        environment:
            POSTGRES_USER: montaan
            POSTGRES_PASSWORD: montaan

    backend:
        build:
            context: ./
            dockerfile: backend/Dockerfile.production
        working_dir: /backend
        command: yarn start
        ports:
            - 8888:8008
        restart: always
        depends_on:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    pgdata:
        driver: local
    pgconf:
        driver: local
    pglog:
        driver: local
