version: '3.1'

services:
    db:
        image: postgres
        volumes:
            - ./database/pgdata:/var/lib/postgresql/data
            - ./database/pgconf:/etc/postgresql
            - ./database/pglog:/var/log/postgresql
        restart: always
        environment:
            POSTGRES_USER: montaan
            POSTGRES_PASSWORD: montaan

    backend:
        build: ./backend
        working_dir: /backend
        command: yarn watch
        ports:
            - 8008:8008
        restart: always
        depends_on:
            - db
        volumes:
            - ./backend:/backend
            - /backend/node_modules

    frontend:
        build: ./frontend
        working_dir: /frontend
        command: yarn start
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - backend
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
